version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_DB: rodrigo
      POSTGRES_USER: rodrigo
      POSTGRES_PASSWORD: senha123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "rodrigo", "-d", "rodrigo"]
      interval: 10s
      timeout: 5s
      retries: 5

  django:
    build: ./backend
    container_name: django_backend
    command: /app/entrypoint.sh
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      angular:
        condition: service_started
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_NAME=rodrigo
      - DB_USER=rodrigo
      - DB_PASSWORD=senha123
    restart: always
    networks:
      - app_network
  angular:
    build: ./frontend/
    container_name: angular_frontend
    command: npm start -- --host 0.0.0.0
    volumes:
      - ./frontend:/app
    ports:
      - "4200:4200"
    networks:
      - app_network
    restart: always
networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
